modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
enumExtensions="META-INF/enumextensions.json"

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A name name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config = "jolcraft.mixins.json"