package net.sievert.jolcraft.datagen.client.model.subprovider;

import net.minecraft.client.color.item.Dye;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.model.ItemModelUtils;
import net.minecraft.client.data.models.model.ModelTemplates;
import net.minecraft.client.data.models.model.TextureMapping;
import net.minecraft.client.renderer.item.ItemModel;
import net.minecraft.client.renderer.item.SelectItemModel;
import net.minecraft.client.renderer.item.properties.select.TrimMaterialProperty;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.equipment.ArmorMaterial;
import net.minecraft.world.item.equipment.ArmorMaterials;
import net.minecraft.world.item.equipment.EquipmentAsset;
import net.minecraft.world.item.equipment.trim.TrimMaterial;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.neoforge.registries.DeferredItem;
import net.sievert.jolcraft.data.language.JolCraftDictionary;
import net.sievert.jolcraft.datagen.client.model.util.AbstractModelProvider;
import net.sievert.jolcraft.util.JolCraftStrings;
import net.sievert.jolcraft.world.item.JolCraftItems;
import net.sievert.jolcraft.world.item.material.JolCraftMaterials;
import net.sievert.jolcraft.world.item.material.trim.JolCraftTrimMaterials;
import net.sievert.jolcraft.world.item.util.equipment.JolCraftEquipmentHelper;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

@OnlyIn(Dist.CLIENT)
public final class TrimModelSubProvider implements AbstractModelProvider.ModelSubProvider {

    private final HolderLookup.Provider registries;

    public TrimModelSubProvider(HolderLookup.Provider registries) {
        this.registries = registries;
    }

    // -------------------------------------------------------------------------
    // Types
    // -------------------------------------------------------------------------

    /**
     * Vanilla armor spec derived from canonical vanilla ArmorMaterials constants,
     * not magic strings.
     */
    private record VanillaArmorSpec(@NotNull String baseName, boolean dyeable) {
    }

    // -------------------------------------------------------------------------
    // Constants
    // -------------------------------------------------------------------------

    private static final Dye LEATHER_DYE_TINT = new Dye(-6265536);

    /**
     * Trims we add on top of vanilla:
     * - JolCraft base materials (derived from JolCraftMaterials.Material)
     * - JolCraft attribute trims (derived from JolCraftTrimMaterials.Attribute)
     */
    private static final List<ItemModelGenerators.TrimMaterialData> CUSTOM_TRIMS = buildCustomTrims();

    /**
     * All trims used for select() cases:
     * - Vanilla trims (already shipped by Minecraft)
     * - JolCraft trims (generated by us for both JolCraft armor and vanilla armor)
     */
    private static final List<ItemModelGenerators.TrimMaterialData> ALL_TRIMS = buildAllTrims();

    /**
     * Canonical vanilla armor identity. Base names are derived from ArmorMaterial.assetId().
     */
    private static final List<VanillaArmorSpec> VANILLA_ARMOR_SETS = buildVanillaArmorSets();

    /**
     * JolCraft armor sets keyed by canonical material identity.
     * This connects "material getId + equipment asset key" to the actual registered items.
     * NOTE: We deliberately source the items from JolCraftItems.ARMOR_SETS.
     * The only "mapping" here is which material corresponds to which entry in ARMOR_SETS.
     */
    private static final Map<JolCraftMaterials.Material, JolCraftEquipmentHelper.ArmorSet<DeferredItem<Item>>> ARMOR_BY_MATERIAL =
            buildArmorByMaterial();

    // -------------------------------------------------------------------------
    // ModelSubProvider
    // -------------------------------------------------------------------------

    @Override
    public void addModels(@NotNull BlockModelGenerators blocks, @NotNull ItemModelGenerators items) {
        items.generateFlatItem(JolCraftItems.FORGE_ARMOR_TRIM_SMITHING_TEMPLATE.get(), ModelTemplates.FLAT_ITEM);

        // JolCraft armor (generated in the equipment asset namespace)
        for (var entry : ARMOR_BY_MATERIAL.entrySet()) {
            generateJolCraftArmorSet(items, entry.getKey(), entry.getValue());
        }

        // Vanilla armor (generated in minecraft namespace, only adding missing custom trim variants)
        for (VanillaArmorSpec spec : VANILLA_ARMOR_SETS) {
            generateVanillaArmorSet(items, registries, spec);
        }
    }

    // -------------------------------------------------------------------------
    // JolCraft armor generation
    // -------------------------------------------------------------------------

    private static void generateJolCraftArmorSet(
            @NotNull ItemModelGenerators itemModels,
            @NotNull JolCraftMaterials.Material material,
            @NotNull JolCraftEquipmentHelper.ArmorSet<DeferredItem<Item>> set
    ) {
        String baseName = material.id();
        ResourceKey<EquipmentAsset> equipmentAssetKey = material.equipmentAssetKey();

        for (JolCraftEquipmentHelper.ArmorPiece piece : JolCraftEquipmentHelper.ArmorPiece.values()) {
            String fileName = baseName + "_" + piece.suffix();

            ResourceLocation baseModelLoc = ResourceLocation.fromNamespaceAndPath(
                    equipmentAssetKey.location().getNamespace(),
                     JolCraftDictionary.ITEM + "/" + fileName
            );
            ResourceLocation baseTexture = ResourceLocation.fromNamespaceAndPath(
                    equipmentAssetKey.location().getNamespace(),
                    JolCraftDictionary.ITEM + "/" + fileName
            );

            // Variant model JSONs (we generate for ALL trims, including vanilla trims)
            for (ItemModelGenerators.TrimMaterialData data : ALL_TRIMS) {
                ResourceLocation variantModelLoc = baseModelLoc.withSuffix("_" + data.name() + "_" + JolCraftDictionary.TRIM);
                ResourceLocation trimTexture = trimTextureLocation(piece, data, equipmentAssetKey);
                itemModels.generateLayeredItem(variantModelLoc, baseTexture, trimTexture);
            }

            // Base model JSON
            ModelTemplates.FLAT_ITEM.create(
                    baseModelLoc,
                    TextureMapping.layer0(baseTexture),
                    itemModels.modelOutput
            );

            // select() cases
            ItemModel.Unbaked defaultModel = ItemModelUtils.plainModel(baseModelLoc);

            List<SelectItemModel.SwitchCase<ResourceKey<TrimMaterial>>> cases = new ArrayList<>(ALL_TRIMS.size());
            for (ItemModelGenerators.TrimMaterialData data : ALL_TRIMS) {
                ResourceLocation variantModelLoc = baseModelLoc.withSuffix("_" + data.name() + "_" + JolCraftDictionary.TRIM);
                cases.add(ItemModelUtils.when(data.materialKey(), ItemModelUtils.plainModel(variantModelLoc)));
            }

            Item armorItem = set.get(piece).get();
            itemModels.itemModelOutput.accept(
                    armorItem,
                    ItemModelUtils.select(new TrimMaterialProperty(), defaultModel, cases)
            );
        }
    }

    /**
     * IMPORTANT:
     * Your working setup expects ALL trim textures to be in the *minecraft* trims folder:
     *   minecraft:textures/trims/items/<piece>_trim_<name>.png
     * That applies to BOTH vanilla trims and your attribute trims.
     */
    private static @NotNull ResourceLocation trimTextureLocation(
            @NotNull JolCraftEquipmentHelper.ArmorPiece piece,
            @NotNull ItemModelGenerators.TrimMaterialData data,
            @NotNull ResourceKey<EquipmentAsset> equipmentAssetKey
    ) {
        String trimTextureName = data.name();

        String overrideName = data.overrideArmorMaterials().get(equipmentAssetKey);
        if (overrideName != null && !overrideName.isEmpty()) {
            trimTextureName = overrideName;
        }

        return ResourceLocation.withDefaultNamespace(
                JolCraftStrings.slashed(JolCraftStrings.plural(JolCraftDictionary.TRIM), JolCraftStrings.plural(JolCraftDictionary.ITEM)) + "/" + piece.suffix() + "_" + JolCraftDictionary.TRIM + "_" + trimTextureName
        );
    }

    // -------------------------------------------------------------------------
    // Vanilla armor generation
    // -------------------------------------------------------------------------

    private static void generateVanillaArmorSet(
            @NotNull ItemModelGenerators itemModels,
            @NotNull HolderLookup.Provider registries,
            @NotNull VanillaArmorSpec spec
    ) {
        String baseName = spec.baseName();
        boolean dyeable = spec.dyeable();

        for (JolCraftEquipmentHelper.ArmorPiece piece : JolCraftEquipmentHelper.ArmorPiece.values()) {
            String fileName = baseName + "_" + piece.suffix();

            ResourceLocation vanillaBaseModelLoc = ResourceLocation.withDefaultNamespace(JolCraftDictionary.ITEM + "/" + fileName);
            ResourceLocation vanillaBaseTexture = ResourceLocation.withDefaultNamespace(JolCraftDictionary.ITEM + "/" + fileName);
            ResourceLocation vanillaOverlayTexture = ResourceLocation.withDefaultNamespace(JolCraftDictionary.ITEM + "/" + fileName + "_" + JolCraftDictionary.OVERLAY);

            // 1) Generate missing CUSTOM trim variant models in minecraft namespace (same place vanilla expects)
            for (ItemModelGenerators.TrimMaterialData data : CUSTOM_TRIMS) {
                ResourceLocation variantModelLoc = ResourceLocation.withDefaultNamespace(
                        JolCraftDictionary.ITEM + "/" + fileName + "_" + data.name() + "_" + JolCraftDictionary.TRIM
                );

                ResourceLocation trimTexture = vanillaTrimTextureLocation(piece, data.name());

                if (dyeable) {
                    itemModels.generateLayeredItem(variantModelLoc, vanillaBaseTexture, vanillaOverlayTexture, trimTexture);
                } else {
                    itemModels.generateLayeredItem(variantModelLoc, vanillaBaseTexture, trimTexture);
                }
            }

            // 2) select() cases (vanilla trim models already exist; CUSTOM ones we generated above)
            List<SelectItemModel.SwitchCase<ResourceKey<TrimMaterial>>> cases = new ArrayList<>(ALL_TRIMS.size());
            for (ItemModelGenerators.TrimMaterialData data : ALL_TRIMS) {
                ResourceLocation variantModelLoc = ResourceLocation.withDefaultNamespace(
                        JolCraftDictionary.ITEM + "/" + fileName + "_" + data.name() + "_" + JolCraftDictionary.TRIM
                );

                ItemModel.Unbaked baked = dyeable
                        ? ItemModelUtils.tintedModel(variantModelLoc, LEATHER_DYE_TINT)
                        : ItemModelUtils.plainModel(variantModelLoc);

                cases.add(ItemModelUtils.when(data.materialKey(), baked));
            }

            // 3) Default/fallback = vanilla base (tinted for leather)
            ItemModel.Unbaked defaultModel = dyeable
                    ? ItemModelUtils.tintedModel(vanillaBaseModelLoc, LEATHER_DYE_TINT)
                    : ItemModelUtils.plainModel(vanillaBaseModelLoc);

            Item armorItem = vanillaArmorItem(registries, baseName, piece);
            itemModels.itemModelOutput.accept(
                    armorItem,
                    ItemModelUtils.select(new TrimMaterialProperty(), defaultModel, cases)
            );
        }
    }

    private static @NotNull ResourceLocation vanillaTrimTextureLocation(
            @NotNull JolCraftEquipmentHelper.ArmorPiece piece,
            @NotNull String trimName
    ) {
        return ResourceLocation.withDefaultNamespace(
                JolCraftStrings.slashed(JolCraftStrings.plural(JolCraftDictionary.TRIM), JolCraftStrings.plural(JolCraftDictionary.ITEM)) + "/" + piece.suffix() + "_" + JolCraftDictionary.TRIM + "_" + trimName
        );
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static @NotNull Map<JolCraftMaterials.Material, JolCraftEquipmentHelper.ArmorSet<DeferredItem<Item>>> buildArmorByMaterial() {
        EnumMap<JolCraftMaterials.Material, JolCraftEquipmentHelper.ArmorSet<DeferredItem<Item>>> out = new EnumMap<>(JolCraftMaterials.Material.class);
        out.put(JolCraftMaterials.Material.DEEPSLATE, JolCraftItems.DEEPSLATE_ARMOR_SET);
        out.put(JolCraftMaterials.Material.MITHRIL, JolCraftItems.MITHRIL_ARMOR_SET);
        return Map.copyOf(out);
    }

    private static @NotNull List<ItemModelGenerators.TrimMaterialData> buildCustomTrims() {
        List<ItemModelGenerators.TrimMaterialData> out = new ArrayList<>();

        // Base material trims (with per-armor override = "<getId>_darker" for same-material armor)
        for (JolCraftMaterials.Material material : JolCraftMaterials.Material.values()) {
            Map<ResourceKey<EquipmentAsset>, String> overrides =
                    Map.of(material.equipmentAssetKey(), material.darkerTrimName());

            out.add(new ItemModelGenerators.TrimMaterialData(
                    material.id(),
                    JolCraftTrimMaterials.vanilla(material),
                    overrides
            ));
        }

        // Attribute trims (no overrides)
        for (JolCraftTrimMaterials.Attribute attribute : JolCraftTrimMaterials.Attribute.values()) {
            out.add(new ItemModelGenerators.TrimMaterialData(
                    attribute.id(),
                    JolCraftTrimMaterials.attribute(attribute),
                    Map.of()
            ));
        }

        return List.copyOf(out);
    }

    private static @NotNull List<ItemModelGenerators.TrimMaterialData> buildAllTrims() {
        List<ItemModelGenerators.TrimMaterialData> out = new ArrayList<>(ItemModelGenerators.TRIM_MATERIAL_MODELS);
        out.addAll(CUSTOM_TRIMS);
        return List.copyOf(out);
    }

    private static @NotNull Item vanillaArmorItem(
            @NotNull HolderLookup.Provider registries,
            @NotNull String baseName,
            @NotNull JolCraftEquipmentHelper.ArmorPiece piece
    ) {
        String itemName = baseName + "_" + piece.suffix();
        ResourceLocation id = ResourceLocation.withDefaultNamespace(itemName);

        ResourceKey<Item> key = ResourceKey.create(Registries.ITEM, id);

        return registries.lookupOrThrow(Registries.ITEM)
                .get(key)
                .map(Holder::value)
                .orElseThrow(() -> new IllegalStateException("Vanilla armor item not found: " + itemName));
    }

    private static @NotNull List<VanillaArmorSpec> buildVanillaArmorSets() {
        List<ArmorMaterial> mats = List.of(
                ArmorMaterials.LEATHER,
                ArmorMaterials.CHAINMAIL,
                ArmorMaterials.IRON,
                ArmorMaterials.GOLD,
                ArmorMaterials.DIAMOND,
                ArmorMaterials.NETHERITE
        );

        List<VanillaArmorSpec> out = new ArrayList<>(mats.size());
        for (ArmorMaterial mat : mats) {
            out.add(new VanillaArmorSpec(
                    vanillaArmorBaseName(mat),
                    mat == ArmorMaterials.LEATHER
            ));
        }
        return List.copyOf(out);
    }

    /**
     * Derive the item base name from the ArmorMaterial's canonical equipment asset getId.
     * NOTE:
     * - Vanilla uses "golden_*" item ids for GOLD (asset getId path = "gold").
     * - Everything else matches the asset getId path ("leather", "iron", "diamond", "netherite", "chainmail", etc).
     */
    private static @NotNull String vanillaArmorBaseName(@NotNull ArmorMaterial material) {
        String path = material.assetId().location().getPath();
        if (path.equals(JolCraftDictionary.GOLD)) return JolCraftDictionary.GOLD + "en";
        return path;
    }
}